workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: cd reels_counter && flutter pub get
      - name: Build APK
        script: cd reels_counter && flutter build apk --release --no-shrink
    artifacts:
      - reels_counter/build/app/outputs/flutter-apk/app-release.apk
